###
POST http://localhost:3000/api/v1/categories HTTP/1.1
Content-Type: application/json

{
        "name": "Sci Fi"
}

###
GET http://localhost:3000/api/v1/categories HTTP/1.1

###
GET http://localhost:3000/api/v1/categories/6264b4507e604d486bdc13aa HTTP/1.1

###
PUT http://localhost:3000/api/v1/categories/6264b4507e604d486bdc13ba HTTP/1.1
Content-Type: application/json

{
        "name": "thriller",
}

###
DELETE http://localhost:3000/api/v1/categories/6264be5c2ef15ccdd9d78fac HTTP/1.1
